### ISSUE TITLE
Can you see any change in parse_video

### ISSUE THREAD

**Issue by mastervolkov** [barneyman/somagic#4]
Unable add pull reguest to you, but have some performance and get stable img

(I test on motion - and in 10 Fps they get laggy img - with thet patch - all work)

https://github.com/mastervolkov/smi2021/pull/1
or simple
master in https://github.com/mastervolkov/smi2021

**Comment by barneyman** [comment]
thanks very much

i'll take a look

**Comment by mastervolkov** [comment]
Yes. Sorry for my bad english.

I send these to https://github.com/jonjonarnearne/smi2021 (they do work in
subfolder drivers/media/usb/smi2021).
And dublicate that to You for simplification understand (i try compare my
and you repo for build patch, but too many changes).

Current trunk have some problem:
1. get_buf not allways return buffer, but if buffer adsent - start position
(buf->pos) lost (stay zero)- as result, first (odd) frame draw not from
first line.
I fix these - if buffer need, but not alloced - skip thet frame and send in
buffer next frame. Result is all frame good ( i test and use that in my
motion with 10 fps - all excellent - problem adsent
2. Copy_video do copy by 1 byte - thet not optimal - i change to memcpy
3. All line from device is 1440 ( performance improvement here) - i change
processing find trc to block 1440 + 3 = total (by oprofile) performance
faster at x20.

Patch in mail attach

P.S. Is you work together with jonjonarnearne or it is completely different
drivers?

2015-04-01 2:30 GMT+03:00 barneyman notifications@github.com:

> thanks very much
> 
> i'll take a look
>

**Comment by mastervolkov** [comment]
All these change added in https://github.com/Manouchehri/smi2021 - can you check these?

**Comment by mastervolkov** [comment]
Sorry, You already do block copy. Just a little different :)
